# GitHub Action for generating a contribution graph with a snake eating your contributions

name: Generate Snake

on:
  # Runs every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: AkashAnuragi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Push the generated files to the `output` branch
      - name: Push snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
